# Emscripten build: provided by the emscripten port (-sUSE_VORBIS=1), no library search needed.
if(NOT TARGET Vorbis::vorbis)
    add_library(Vorbis::vorbis INTERFACE IMPORTED GLOBAL)
    set_target_properties(Vorbis::vorbis PROPERTIES INTERFACE_COMPILE_OPTIONS "-sUSE_VORBIS=1" INTERFACE_LINK_OPTIONS "-sUSE_VORBIS=1")
endif()
if(NOT TARGET Vorbis::vorbisenc)
    add_library(Vorbis::vorbisenc INTERFACE IMPORTED GLOBAL)
    set_target_properties(Vorbis::vorbisenc PROPERTIES INTERFACE_COMPILE_OPTIONS "-sUSE_VORBIS=1" INTERFACE_LINK_OPTIONS "-sUSE_VORBIS=1")
endif()
if(NOT TARGET Vorbis::vorbisfile)
    add_library(Vorbis::vorbisfile INTERFACE IMPORTED GLOBAL)
    set_target_properties(Vorbis::vorbisfile PROPERTIES INTERFACE_COMPILE_OPTIONS "-sUSE_VORBIS=1" INTERFACE_LINK_OPTIONS "-sUSE_VORBIS=1")
endif()
set(Vorbis_FOUND TRUE)
set(Vorbis_INCLUDE_DIRS "")
set(Vorbis_LIBRARIES "")
